<?php

// generated by automodel

final class UserLookupModel extends \Model\Base\ActiveRecord implements \Consts\ColumnConst {
    public static $table = 'UserLookup';
    public static $pool = 'lookup';

    public static $columns = array(
    
        array(
            self::NAME     => 'entityId',
            self::TYPE     => self::INTEGER,
            self::PK       => true,
        ),
        
        array(
            self::NAME     => 'accountName',
            self::TYPE     => self::STRING,
        ),
        
        array(
            self::NAME     => 'accountPassword',
            self::TYPE     => self::STRING,
        ),
        
        array(
            self::NAME     => 'deviceUUID',
            self::TYPE     => self::STRING,
        ),
        
        array(
            self::NAME     => 'shardId',
            self::TYPE     => self::INTEGER,
        ),
        
        array(
            self::NAME     => 'shardLock',
            self::TYPE     => self::INTEGER,
        ),
        
        array(
            self::NAME     => 'ctime',
            self::TYPE     => self::DATETIME,
        ),
        
        array(
            self::NAME     => 'mtime',
            self::TYPE     => self::DATETIME,
        ),
        
    );

}

